export class Constants {
    static DEFAULT_ROW_HEIGHT = 24;
    static DEFAULT_COLUMN_WIDTH = 80;
    static MAX_ROWS = 100000;
    static MAX_COLS = 5000;
    static ROW_HEADER_WIDTH = 60;
    static COLUMN_HEADER_WIDTH = 30;
    static CELLS_BG_COLOR = '#ffffff';
    static CELLS_BORDER_COLOR = '#71797E';
    static CELLS_VALUE_FONT_COLOR = '#2c3e50';
    static HEADER_SELECTED_BG_COLOR = '#107c41';
    static HEADER_NOT_SELECTED_BG_COLOR = '#ecf0f1';
    static HEADER_NOT_SELECTED_FONT_COLOR = '#616161';
    static HEADER_TOP_LEFT_BG_COLOR = '#e0e0e0';
    static HEADER_TOP_LEFT_BORDER_COLOR = '#bdbdbd';
    static HEADER_HIGHLIGHT_BG_COLOR = '#caead8';
    static HEADER_HIGHLIGHT_BORDER_COLOR = '#107c41';
    static HEADER_HIGHLIGHT_FONT_COLOR = '#1b703b';
}